### ISSUE TITLE
Document how to build.

### ISSUE THREAD

**Issue by garyvdm** [Plonk42/mytracks#7]
So I work mostly with python, and I'm a Java/Android noob. I'm had a hard time to figure out how to build the project. 

In particular, I've hit this error:

```
.../myTracks/build/intermediates/manifests/full/debug/AndroidManifest.xml:155:28-50: AAPT: No resource found that matches the given name (at 'value' with value '@string/backup_api_key').

.../myTracks/build/intermediates/manifests/full/debug/AndroidManifest.xml:159:28-47: AAPT: No resource found that matches the given name (at 'value' with value '@string/maps_apikey').
```

I created an api key through the google console, but then I'm not sure where to put it. (In order to get past this issue, I've put the apikey directly into `myTracks/src/main/AndroidManifest.xml`, but this is not a good solution because it is easily to accidentally commit this.)

**Comment by Plonk42** [comment]
Hi,

Google Map API key was moved into it own file, added to .gitignore. The file is `myTracks/src/main/res/values/apikeys.xml` which of course you will not find because it is ignored  (this was done in 4639b209). You have to create it in your project.

I will add a section on the README to explain that.

**Comment by Plonk42** [comment]
I have added "How to build" section to the README. See: https://github.com/Plonk42/mytracks#how-to-build

**Comment by Plonk42** [comment]
BTW `maps_apikey` is now called `maps_api_key` to be consistent with `backup_api_key`.

**Comment by garyvdm** [comment]
Thanks!
